name: flutter_blob
description: A blob generator for flutter apps
version: 0.0.1
homepage: https://github.com/g-apparence/shader_blob

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: 
   assets:
    - assets/shaders/
